import Head from "next/head";
import Image from "next/image";
import CardLg from "../components/Card/CardLg";
import CardMd from "../components/Card/CardMd";
import CardSm from "../components/Card/CardSm";
import image1 from "../public/assets/images/photo.jpeg";
import image2 from "../public/assets/images/photo2.jpeg";
import image3 from "../public/assets/images/photo3.jpeg";
import image4 from "../public/assets/images/photo4.jpg";
export default function Home({ data, first }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Home</title>
      </Head>
      
      <main>
        <section className="container py-4 justify-center flex-wrap  flex gap-5">
          {data.map((item, i) => (
            <CardSm
              key={i}
              title={item.title}
              author={item.author}
              image={image1}
            />
          ))}
        </section>
        <section className="container flex justify-center my-12">
          <CardLg
            title={first.title}
            image={image2}
            content={first.content}
            author={first.author}
            tags={first.tags}
          />
        </section>
        <section className="container flex justify-center gap-5 flex-wrap my-12">
        {data.map((item, i) => (
            <CardSm
              key={i}
              title={item.title}
              author={item.author}
              image={image1}
            />
          ))}
        </section>
        <section className="flex flex-wrap gap-12 justify-center">
          <CardMd
            image={image1}
            title={first.title}
            content={first.content}
            author={first.author}
          />
          <CardMd
            image={image2}
            title={first.title}
            content={first.content}
            author={first.author}
          />
          <CardMd
            image={image3}
            title={first.title}
            content={first.content}
            author={first.author}
          />
          <CardMd
            image={image4}
            title={first.title}
            content={first.content}
            author={first.author}
          />
        </section>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/blogs");
  const data = await res.json();
  const first = data[0];
  return {
    props: { data, first },
  };
}
