import Head from "next/head";
import Image from "next/image";
import CardMd from "../components/Card/CardMd";
import CardSm from "../components/Card/CardSm";
import image1 from "../public/assets/images/photo.jpeg";
import image2 from "../public/assets/images/photo2.jpeg";
import image3 from "../public/assets/images/photo3.jpeg";
import image4 from "../public/assets/images/photo4.jpg";
export default function Home({ data, first }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Home</title>
      </Head>
      
      <main>
        <section className="container py-4 justify-center flex-wrap  flex gap-5">
          {data.map((item, i) => (
            <CardSm
              key={i}
              title={item.title}
              author={item.author}
              image={image1}
            />
          ))}
        </section>
        <section className="container flex justify-center">
          <div className="max-w-[1200px] flex justify-center gap-5">
            <div className="blog-img flex justify-center overflow-hidden w-[50%] h-96">
              <Image className="object-cover rounded-xl hover:rounded-2xl min-w-[100%] min-h-[100%] duration-300" src={image2} alt="creative" />
            </div>
            <div className="blog-content w-[50%] p-4">
              <div className="tags mb-8">
                {first.tags.map((item, i) => (
                  <span className="mr-2 px-3 py-2 rounded-xl bg-slate-200 text-slate-800 font-bold">{item}</span>
                ))}
              </div>
              <h3 className="blog-main-title mb-6 font-black text-5xl">{first.title}</h3>
              <p className="font-semibold mb-6">{first.content}</p>
              <div className="author">
                {first.author.map((item, i) => (
                  <span className="mr-2 rounded-md bg-amber-400 text-stone-800 px-3 py-2 font-semibold ">{item}</span>
                ))}
              </div>
            </div>
          </div>
        </section>
        <section className="container flex justify-center gap-5 flex-wrap">
        {data.map((item, i) => (
            <CardSm
              key={i}
              title={item.title}
              author={item.author}
              image={image1}
            />
          ))}
        </section>
        <section className="flex flex-wrap gap-4 justify-center">
          <CardMd
            image={image1}
            title={first.title}
            content={first.content}
            author={first.author}
          />
          <CardMd
            image={image2}
            title={first.title}
            content={first.content}
            author={first.author}
          />
          <CardMd
            image={image3}
            title={first.title}
            content={first.content}
            author={first.author}
          />
          <CardMd
            image={image4}
            title={first.title}
            content={first.content}
            author={first.author}
          />
        </section>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/blogs");
  const data = await res.json();
  const first = data[0];
  return {
    props: { data, first },
  };
}
