import Head from 'next/head'
import Image from 'next/image'
import CardSm from '../components/Card/CardSm'
import image1 from '../public/assets/images/photo.jpeg'

export default function Home({data}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main> 
        <section className='container py-4 justify-center flex-wrap  flex gap-5'>
        {
          data.map((items,i)=>(
            <CardSm
            key={i}
          title={items.title}
          author={items.author}
          image={image1}
        />
          ))
        }
        
        
        </section>
      </main>
    </>
  )
}


export async function getServerSideProps(){
  const res = await fetch('http://localhost:3000/api/blogs');
  const data = await res.json();

  return{
    props: {data},
  }
}